import JustLogo from '@/assets/JustLogo.svg';
import AlphaLogo from '@/assets/AlphaLogo.svg';

export const cookingSoonMeals = [
  {
    id: '1',
    title: 'Egusi Soup',
    image: require('@/assets/meals/Egusi.png'),
    cookingTime: 'Cooking Today',
    moq: 'MOQ - 3L',
    price: '₦5,000/1L',
    portionsLeft: 3,
  },
  {
    id: '2',
    title: 'Spaghetti',
    image: require('@/assets/meals/Spaghetti.jpg'),
    cookingTime: 'Cooking Today',
    moq: 'MOQ - 3L',
    price: '₦5,000/1L',
  },
  {
    id: '3',
    title: 'Spaghetti',
    image: require('@/assets/meals/Amala.png'),
    cookingTime: 'Cooking Today',
    moq: 'MOQ - 3L',
    price: '₦5,000/1L',
  },
];

export const readyNowMeals = [
  {
    id: '1',
    title: 'Spicy smoky jollof rice',
    image: require('@/assets/home/spicysmoky.png'),
    cookingTime: 'Cooking Today',
    moq: 'MOQ - 3L',
    price: '₦15,000',
    priceUnit: '5L',
    portionsLeft: 0,
  },
  {
    id: '2',
    title: 'Spaghetti',
    image: require('@/assets/home/meatplater.png'),
    cookingTime: 'Cooking Today',
    moq: 'MOQ - 3L',
    price: '₦25,000',
    priceUnit: '1L',
    portionsLeft: 3,
  },
  {
    id: '3',
    title: 'Spaghetti',
    image: require('@/assets/home/bbq.png'),
    cookingTime: 'Cooking Today',
    moq: 'MOQ - 3L',
    price: '₦5,000',
    priceUnit: '1L',
    portionsLeft: 3,
  },
];

export const discoverMeals = [
  {
    id: '1',
    title: 'Egusi Soup',
    image: require('@/assets/meals/PepperedChicken.png'),
    cookingTime: 'Cooking Today',
    moq: 'MOQ - 3L',
    price: '₦5,000/1L',
    portionsLeft: 3,
  },
  {
    id: '2',
    title: 'Spaghetti',
    image: require('@/assets/meals/Chicken.png'),
    cookingTime: 'Cooking Today',
    moq: 'MOQ - 3L',
    price: '₦5,000/1L',
  },
  {
    id: '3',
    title: 'Spaghetti',
    image: require('@/assets/meals/Amala.png'),
    cookingTime: 'Cooking Today',
    moq: 'MOQ - 3L',
    price: '₦5,000/1L',
  },
];

export const breakfastMeals = [
  {
    id: '1',
    title: 'Egusi Soup',
    image: require('@/assets/meals/Akara.png'),
    cookingTime: 'Cooking Today',
    moq: 'MOQ - 3L',
    price: '₦5,000/1L',
    portionsLeft: 3,
  },
  {
    id: '2',
    title: 'Spaghetti',
    image: require('@/assets/meals/Dodo.png'),
    cookingTime: 'Cooking Today',
    moq: 'MOQ - 3L',
    price: '₦5,000/1L',
  },
  {
    id: '3',
    title: 'Spaghetti',
    image: require('@/assets/meals/Amala.png'),
    cookingTime: 'Cooking Today',
    moq: 'MOQ - 3L',
    price: '₦5,000/1L',
  },
];

export const partyMeals = [
  {
    id: '1',
    title: 'Egusi Soup',
    image: require('@/assets/meals/Chips.png'),
    cookingTime: 'Cooking Today',
    moq: 'MOQ - 3L',
    price: '₦5,000/1L',
    portionsLeft: 3,
  },
  {
    id: '2',
    title: 'Spaghetti',
    image: require('@/assets/meals/Amala.png'),
    cookingTime: 'Cooking Today',
    moq: 'MOQ - 3L',
    price: '₦5,000/1L',
  },
  {
    id: '3',
    title: 'Spaghetti',
    image: require('@/assets/meals/Amala.png'),
    cookingTime: 'Cooking Today',
    moq: 'MOQ - 3L',
    price: '₦5,000/1L',
  },
];

// Mock data for the kitchen-based home screen

export const kitchensData = [
  {
    id: 'kitchen_1',
    kitchenName: "Munachi's Kitchen",
    kitchenImage: require('@/assets/home/Muna1.png'),
    rating: 4.7,
    reviewCount: 98,
    location: 'Lekki, Lagos',
    pickupAvailable: true,
    deliveryAvailable: false,
    // deliveryCost: 'N3,000',
    meals: [
      {
        id: 'meal_1_1',
        title: 'Well cooked smoky jollof rice',
        image: require('@/assets/home/SmokyJollof.png'),
        price: '₦25,000',
        priceUnit: '4 Litre',
        cookingTime: 'Cooking Tomorrow',
        portionsLeft: 2,
      },
      {
        id: 'meal_1_2',
        title: '16 Pieces of spicy chicken wings',
        image: require('@/assets/home/16pieces.png'),
        price: '₦35,000',
        priceUnit: '16 Litre',
        cookingTime: 'Cooking Tomorrow',
        badge: 'Popular',
      },
      {
        id: 'meal_1_3',
        title: '16 Pieces of spicy chicken wings',
        image: require('@/assets/home/withTomato.png'),
        price: '₦35,000',
        priceUnit: '16 Litre',
        cookingTime: 'Cooking Tomorrow',
        badge: 'Popular',
      },
      {
        id: 'meal_1_4',
        title: '16 Pieces of spicy chicken wings',
        image: require('@/assets/home/16pieces.png'),
        price: '₦35,000',
        priceUnit: '16 Litre',
        cookingTime: 'Cooking Tomorrow',
        badge: 'Popular',
      },

    ],
  },
  {
    id: 'kitchen_2',
    kitchenName: "Munachi's Kitchen",
    kitchenImage: require('@/assets/home/Muna2.png'),
    rating: 4.7,
    reviewCount: 98,
    location: 'Lekki, Lagos',
    pickupAvailable: false,
    deliveryAvailable: true,
    // deliveryCost: 'N3,000',
    meals: [
      {
        id: 'meal_2_1',
        title: 'Full grilled chicken',
        image: require('@/assets/home/grilled.png'),
        priceUnit: '1 Piece',
        price: '₦12,000',
        cookingTime: 'Cooking Wed 22, Jan',
        portionsLeft: 0,
      },
      {
        id: 'meal_2_2',
        title: 'Mixed tray of small chops',
        image: require('@/assets/home/smallchops.png'),
        priceUnit: '1 Pack',
        price: '₦40,000',
        cookingTime: 'Cooking Today',
        portionsLeft: 0,
        badge: 'Popular',
      },
      {
        id: 'meal_2_3',
        title: 'Mixed tray of small chops',
        image: require('@/assets/home/withTomato.png'),                                                                                                                                                                                                                                                    
        priceUnit: '1 Pack',
        price: '₦40,000',
        cookingTime: 'Cooking Today',
        badge: 'Popular',
      },
      {
        id: 'meal_2_4',
        title: 'Mixed tray of small chops',
        image: require('@/assets/home/smallchops.png'),
        priceUnit: '1 Pack',
        price: '₦40,000',
        cookingTime: 'Cooking Today',
      },
    ],
  },
  {
    id: 'kitchen_3',
    kitchenName: "Munachi's Kitchen",
    kitchenImage: require('@/assets/home/Muna3.png'),
    rating: 4.7,
    reviewCount: 98,
    location: 'Lekki, Lagos',
    pickupAvailable: false,
    deliveryAvailable: true,
    // deliveryCost: 'N3,000',
    meals: [
      {
        id: 'meal_2_1',
        title: 'Full grilled chicken',
        image: require('@/assets/home/pie.png'),
        priceUnit: '₦12,000 / 1 Piece',
        cookingTime: 'Cooking Wed 22, Jan',
        price: '₦12,000',
      },
      {
        id: 'meal_2_2',
        title: 'Mixed tray of small chops',
        image: require('@/assets/home/bananacake.png'),
        priceUnit: '₦40,000 / 1 Pack',
        cookingTime: 'Cooking Today',
      },
      {
        id: 'meal_2_3',
        title: 'Mixed tray of small chops',
        image: require('@/assets/home/withTomato.png'),
        priceUnit: '₦40,000 / 1 Pack',
        cookingTime: 'Cooking Today',
        badge: 'Popular',
      },
      {
        id: 'meal_2_4',
        title: 'Mixed tray of small chops',
        image: require('@/assets/home/smallchops.png'),
        priceUnit: '₦40,000 / 1 Pack',
        cookingTime: 'Cooking Today',
      },
    ],
  },
  {
    id: 'kitchen_4',
    kitchenName: "Munachi's Kitchen",
    kitchenImage: require('@/assets/home/Muna4.png'),
    rating: 4.7,
    reviewCount: 98,
    location: 'Lekki, Lagos',
    pickupAvailable: false,
    deliveryAvailable: true,
    // deliveryCost: 'N3,000',
    meals: [
      {
        id: 'meal_2_1',
        title: 'Full grilled chicken',
        image: require('@/assets/home/smallmeats.png'),
        priceUnit: '1 Piece',
        cookingTime: 'Cooking Wed 22, Jan',
        price: '₦12,000',
        badge: 'Popular',
      },
      {
        id: 'meal_2_2',
        title: 'Mixed tray of small chops',
        image: require('@/assets/home/16pieces.png'),
        priceUnit: '1 Pack',
        cookingTime: 'Cooking Today',
        price: '₦12,000',
      },
      {
        id: 'meal_2_3',
        title: 'Mixed tray of small chops',
        image: require('@/assets/home/withTomato.png'),
        priceUnit: '1 Pack',
        cookingTime: 'Cooking Today',
        price: '₦12,000',
        badge: 'Popular',
      },
      {
        id: 'meal_2_4',
        title: 'Mixed tray of small chops',
        image: require('@/assets/home/smallchops.png'),
        priceUnit: '1 Pack',
        cookingTime: 'Cooking Today',
        price: '₦12,000',
      },
    ],
  },
];

export const recentlyViewedMeals = [
  {
    id: 'recent_1',
    title: 'Spicy smoky jollof rice',
    image: require('@/assets/meals/PepperedChicken.png'),
    priceUnit: '₦15,000 / 5L',
    cookingTime: 'Cooking Today',
  },
  {
    id: 'recent_2',
    title: 'Meat Plater',
    image: require('@/assets/meals/ObeAta.png'),
    priceUnit: '₦25,000 / 1 Pack',
    cookingTime: 'Cooking Today',
    portionsLeft: 3,
  },
  {
    id: 'recent_3',
    title: 'BBQ Chicken wings',
    image: require('@/assets/meals/Egusi.png'),
    priceUnit: '₦5,000',
    cookingTime: 'Cooking Today',
    portionsLeft: 3,
  },
];

export const additionalKitchens = [
  {
    id: 'kitchen_3',
    kitchenName: "Munachi's Kitchen",
    kitchenImage: require('@/assets/meals/Chips.png'),
    rating: 4.7,
    reviewCount: 98,
    location: 'Lekki, Lagos',
    pickupAvailable: true,
    deliveryAvailable: true,
    // deliveryCost: 'N3,000',
    meals: [
      {
        id: 'meal_3_1',
        title: '5 litre of only Egusi Soup, no swallow',
        image: require('@/assets/meals/Egusi.png'),
        priceUnit: '₦8,600 / 12 Pieces',
        cookingTime: 'Cooking Sat 30, Jan',
        portionsLeft: 1,
      },
      {
        id: 'meal_3_2',
        title: 'Well baked banana bread',
        image: require('@/assets/meals/Spaghetti.jpg'),
        priceUnit: '₦25,000',
        cookingTime: 'Cooking Tomorrow',
      },
    ],
  },
  {
    id: 'kitchen_4',
    kitchenName: "Munachi's Kitchen",
    kitchenImage: AlphaLogo,
    rating: 4.7,
    reviewCount: 98,
    location: 'Lekki, Lagos',
    pickupAvailable: true,
    deliveryAvailable: true,
    // deliveryCost: 'N3,000',
    meals: [
      {
        id: 'meal_4_1',
        title: 'Full grilled chicken',
        image: require('@/assets/meals/PepperedChicken.png'),
        priceUnit: '₦12,000 / 1 Piece',
        cookingTime: 'Cooking Wed 22, Jan',
        badge: 'Popular',
      },
      {
        id: 'meal_4_2',
        title: '16 Pieces of spicy chicken wings',
        image: require('@/assets/meals/Chicken.png'),
        priceUnit: '₦35,000 / 16 Litre',
        cookingTime: 'Cooking Tomorrow',
      },
    ],
  },
];